use_modular_headers!

platform :ios, '10.0'

target 'ada-analytic-sdk_Example' do
  pod 'ada-analytic-sdk', :path => '../'

  target 'ada-analytic-sdk_Tests' do
    inherit! :search_paths

    
  end
end
